In [1]:
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
filesav = 'D:/Python/1. Nivel I/9/datos//data_credit.csv'
df = pd.read_csv(filesav, 
                 sep=",",
                 encoding="ISO-8859-1")
df.head()

,duration,chist,reason,camt,telephne,lenemp,instrate,perstat,residlen,prpownr,age,housng,numcred,emptype,numliab,customer
0,6.0,5.0,4.0,1169.0,0.0,4.0,4.0,3.0,4.0,1.0,67.0,2.0,2.0,3.0,1.0,1.0
1,48.0,3.0,4.0,5951.0,1.0,2.0,2.0,2.0,2.0,1.0,22.0,2.0,1.0,3.0,1.0,2.0
2,12.0,5.0,7.0,2096.0,1.0,3.0,2.0,3.0,3.0,1.0,49.0,2.0,1.0,2.0,2.0,1.0
3,42.0,3.0,3.0,7882.0,1.0,3.0,2.0,3.0,4.0,2.0,45.0,3.0,1.0,3.0,2.0,1.0
4,24.0,4.0,1.0,4870.0,1.0,2.0,3.0,3.0,4.0,4.0,53.0,3.0,2.0,3.0,2.0,2.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   duration  1000 non-null   float64
 1   chist     1000 non-null   float64
 2   reason    1000 non-null   float64
 3   camt      1000 non-null   float64
 4   telephne  1000 non-null   float64
 5   lenemp    1000 non-null   float64
 6   instrate  1000 non-null   float64
 7   perstat   1000 non-null   float64
 8   residlen  1000 non-null   float64
 9   prpownr   1000 non-null   float64
 10  age       1000 non-null   float64
 11  housng    1000 non-null   float64
 12  numcred   1000 non-null   float64
 13  emptype   1000 non-null   float64
 14  numliab   1000 non-null   float64
 15  customer  1000 non-null   float64
dtypes: float64(16)
memory usage: 125.1 KB

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X, y = df.iloc[:, 0:15].values, df.iloc[:, 15].values

In [6]:
X = df.iloc[:, 0:15].values

In [7]:
y = df.iloc[:, 15].values

In [15]:
X_train, X_test, y_train, y_test = \
    train_test_split(X, #valor de los predictores 
                     y, #valor del target o variable objetivo
                     test_size=0.3, #proporción de datos para datos de entrenamiento
                     stratify=y, #estratificación
                     random_state=0) #semilla

**Normalización**

In [9]:
from sklearn.preprocessing import MinMaxScaler

In [20]:
mms =MinMaxScaler()

In [21]:
x_train_norm = mms.fit_transform(X_train)

**Estandzación**

In [16]:
from sklearn.preprocessing import StandardScaler

In [18]:
sc = StandardScaler() #estsamos guardando la función en el objeto sc

In [19]:
X_train_std = sc.fit_transform(X_train)#entrenamiento

In [22]:
X_test_std = sc.transform(X_test)

In [ ]:
###DF de los datos de entrenamiento estandarizados

In [23]:
df_cont=pd.DataFrame(X_train_std,
                     columns=["duration","chist","reason", "camt", "telephne",
                                         "lenemp","instrate","perstat", "residlen", "prpownr",
                                         "age","housng","numcred","emptype","numliab"])
df_cont.head()

,duration,chist,reason,camt,telephne,lenemp,instrate,perstat,residlen,prpownr,age,housng,numcred,emptype,numliab
0,0.273431,1.377803,-0.744406,-0.277224,-1.199593,0.228874,0.933475,1.851752,0.121235,-0.339904,-0.769416,0.132827,0.986832,0.147072,-0.445679
1,-0.241782,1.377803,-0.744406,0.276215,-1.199593,1.063310,-1.759240,-0.997097,1.033756,-1.287844,-0.250958,-1.726746,2.679927,0.147072,-0.445679
2,0.273431,-0.502240,-0.276016,1.658889,-1.199593,-1.439999,-1.759240,-0.997097,-0.791286,-0.339904,-0.510187,0.132827,-0.706262,0.147072,-0.445679
3,0.273431,-2.382283,1.363351,0.377476,-1.199593,-0.605562,-1.759240,0.427327,1.033756,-1.287844,0.008271,0.132827,2.679927,-1.366903,-0.445679
4,0.273431,-0.502240,-0.744406,-0.641395,-1.199593,-1.439999,0.933475,1.851752,0.121235,-1.287844,-0.250958,0.132827,-0.706262,0.147072,-0.445679

In [ ]:
###DF de los datos de testeo estandarizados

In [24]:
df_cont_test=pd.DataFrame(X_test_std,
                     columns=["duration","chist","reason", "camt", "telephne",
                                         "lenemp","instrate","perstat", "residlen", "prpownr",
                                         "age","housng","numcred","emptype","numliab"])
df_cont_test.head()

,duration,chist,reason,camt,telephne,lenemp,instrate,perstat,residlen,prpownr,age,housng,numcred,emptype,numliab
0,3.364707,-0.50224,-0.041821,2.551092,-1.199593,0.228874,-0.861669,-0.997097,1.033756,-1.287844,-1.287873,0.132827,-0.706262,0.147072,-0.445679
1,0.273431,-0.50224,-0.510211,1.238380,-1.199593,1.897746,0.933475,0.427327,-0.791286,1.555975,-0.596597,1.992399,-0.706262,1.661046,-0.445679
2,0.273431,-0.50224,-0.041821,-0.045612,-1.199593,-1.439999,0.035903,1.851752,-0.791286,0.608036,-1.201464,-1.726746,-0.706262,0.147072,-0.445679
3,-0.756995,-0.50224,-0.041821,0.067433,0.833616,1.063310,-0.861669,0.427327,0.121235,0.608036,0.094680,0.132827,-0.706262,1.661046,-0.445679
4,1.303856,-0.50224,-0.041821,0.969209,0.833616,-0.605562,0.933475,0.427327,-1.703807,0.608036,-1.028645,0.132827,-0.706262,0.147072,-0.445679

**Matriz de correlaciones**

In [25]:
import numpy as np
import math as math
import scipy.stats as stats

df_corr = df_cont.corr(method="pearson")
#df_corr = df_cont.corr()
df_corr

,duration,chist,reason,camt,telephne,lenemp,instrate,perstat,residlen,prpownr,age,housng,numcred,emptype,numliab
duration,1.000000,-0.076000,0.171482,0.615645,-0.180049,0.099967,0.106123,0.003897,0.041850,0.314577,-0.018861,0.153928,-0.007308,0.252479,0.001114
chist,-0.076000,1.000000,-0.086105,-0.060558,-0.020915,0.130637,0.019237,0.048204,0.013098,-0.063783,0.154075,0.081694,0.436512,0.025071,0.028976
reason,0.171482,-0.086105,1.000000,0.141879,-0.116151,0.024089,0.023723,-0.007387,0.006902,0.055240,0.037755,0.094522,0.074690,0.034516,0.009255
camt,0.615645,-0.060558,0.141879,1.000000,-0.301887,0.088360,-0.279371,-0.026608,0.027859,0.300961,0.050640,0.126361,0.038134,0.282926,0.044728
telephne,-0.180049,-0.020915,-0.116151,-0.301887,1.000000,-0.137472,-0.006466,0.007861,-0.087811,-0.192984,-0.125610,-0.126930,-0.065308,-0.373257,-0.019061
lenemp,0.099967,0.130637,0.024089,0.088360,-0.137472,1.000000,0.052770,0.060109,0.295321,0.181755,0.359757,0.215654,0.115225,0.139594,0.050709
instrate,0.106123,0.019237,0.023723,-0.279371,-0.006466,0.052770,1.000000,0.149039,0.058831,0.015850,0.040698,0.052457,0.044896,0.113138,-0.059866
perstat,0.003897,0.048204,-0.007387,-0.026608,0.007861,0.060109,0.149039,1.000000,0.005756,-0.010995,0.000158,0.105953,0.060637,-0.010475,0.113833
residlen,0.041850,0.013098,0.006902,0.027859,-0.087811,0.295321,0.058831,0.005756,1.000000,0.131417,0.265400,0.054197,0.061345,-0.011909,0.061044
prpownr,0.314577,-0.063783,0.055240,0.300961,-0.192984,0.181755,0.015850,-0.010995,0.131417,1.000000,0.058511,0.354891,-0.019954,0.277565,0.026972
age,-0.018861,0.154075,0.037755,0.050640,-0.125610,0.359757,0.040698,0.000158,0.265400,0.058511,1.000000,0.306957,0.137929,0.013174,0.131171
housng,0.153928,0.081694,0.094522,0.126361,-0.126930,0.215654,0.052457,0.105953,0.054197,0.354891,0.306957,1.000000,0.039837,0.133298,0.109210
numcred,-0.007308,0.436512,0.074690,0.038134,-0.065308,0.115225,0.044896,0.060637,0.061345,-0.019954,0.137929,0.039837,1.000000,-0.013308,0.095047
emptype,0.252479,0.025071,0.034516,0.282926,-0.373257,0.139594,0.113138,-0.010475,-0.011909,0.277565,0.013174,0.133298,-0.013308,1.000000,-0.056606
numliab,0.001114,0.028976,0.009255,0.044728,-0.019061,0.050709,-0.059866,0.113833,0.061044,0.026972,0.131171,0.109210,0.095047,-0.056606,1.000000

In [28]:
n = df_cont.shape[0]
p = df_cont.shape[1]

In [29]:
chi2 = -(n-1-(2*p+5)/6)*math.log(np.linalg.det(df_corr))

In [30]:
chi2

1570.825700088011

In [31]:
ddl = p*(p-1)/2

In [33]:
p_valor = stats.chi2.pdf(chi2,ddl)
p_valor

4.4508973687542834e-260

**Las variables sí están correlacionadas**

In [34]:
import numpy as np
import matplotlib.pyplot as plt

cov_mat = np.cov(X_train_std.T) #se calcula la matriz de covarianza del conjunto de datos estandarizado

In [35]:
autovalores, autovectores=np.linalg.eig(cov_mat)

In [36]:
print(autovalores)

[2.60578196 1.85372185 0.25381197 1.29084417 1.23590266 1.13647209
 1.02547872 0.94670645 0.92180491 0.81141704 0.73721234 0.65968383
 0.46793695 0.52060445 0.55407982]

In [41]:
(autovalores[0]/sum(autovalores))*100

17.347062756722426

**Varianza explicada**

In [42]:
from sklearn.decomposition import PCA

In [43]:
pca = PCA()

In [44]:
X_train_pca = pca.fit_transform(X_train_std)

In [49]:
sum(pca.explained_variance_ratio_[0:6])
#varianza explicada por los 6 componentes principales que indica el criterio de Kaiser

0.6090088392520028

**Data de los componentes principales**

In [50]:
pca=PCA(n_components=6)

In [51]:
X_train_pca = pca.fit_transform(X_train_std)

In [52]:
X_train_pca_df = pd.DataFrame(X_train_pca, columns = ["PCA1","PCA2","PCA3","PCA4","PCA5","PCA6"])

In [53]:
X_train_pca_df.head()

       PCA1      PCA2      PCA3      PCA4      PCA5      PCA6
0  0.357958  1.107804 -0.894869 -2.109526  0.172859 -0.553757
1 -0.036130  1.374380 -3.014144  1.105057 -2.313433  0.418935
2  0.235394 -2.478637 -1.244102  1.296728 -0.449891 -0.675197
3  0.071459 -0.197860 -1.056150  1.563974  0.717678  2.345540
4 -0.765311 -0.414793  0.667308 -1.717680  0.566614 -0.350221

In [54]:
df_y = pd.DataFrame(y_train, columns = ["cliente"])

In [55]:
df_final = pd.concat([X_train_pca_df,df_y], axis=1)

In [56]:
df_final.head()

       PCA1      PCA2      PCA3      PCA4      PCA5      PCA6  cliente
0  0.357958  1.107804 -0.894869 -2.109526  0.172859 -0.553757      1.0
1 -0.036130  1.374380 -3.014144  1.105057 -2.313433  0.418935      2.0
2  0.235394 -2.478637 -1.244102  1.296728 -0.449891 -0.675197      1.0
3  0.071459 -0.197860 -1.056150  1.563974  0.717678  2.345540      2.0
4 -0.765311 -0.414793  0.667308 -1.717680  0.566614 -0.350221      1.0